#!/usr/bin/env python3
"""
Fill data/binance/backup/market_data_labeled.csv with Labels (tags) for each currency.
Labels are like: L1, L2, Meme, DeFi, POW, POS, Gaming, etc.
Uses a static mapping from common knowledge; run once to bootstrap the file.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_BINANCE = ROOT / "data" / "binance"
MARKET_DATA_PATH = DATA_BINANCE / "market_data.csv"
LABELED_PATH = DATA_BINANCE / "backup" / "market_data_labeled.csv"

# Base symbol (no USDT, no 1000 prefix) -> labels string (comma-separated tags)
# Categories: L1, L2, Meme, DeFi, POW, POS, Gaming, NFT, Oracle, Privacy, etc.
SYMBOL_LABELS: dict[str, str] = {
    # L1 + consensus
    "BTC": "L1,POW",
    "ETH": "L1,POW",
    "BCH": "L1,POW",
    "LTC": "L1,POW",
    "ETC": "L1,POW",
    "XRP": "L1",
    "XLM": "L1",
    "ADA": "L1,POS",
    "SOL": "L1,POS",
    "AVAX": "L1,POS",
    "DOT": "L1,POS",
    "ATOM": "L1,POS",
    "NEAR": "L1,POS",
    "FTM": "L1,POS",
    "ALGO": "L1,POS",
    "EGLD": "L1,POS",
    "HBAR": "L1",
    "ONE": "L1,POS",
    "KAVA": "L1,POS",
    "FLOW": "L1",
    "ICP": "L1",
    "MINA": "L1",
    "KDA": "L1,POW",
    "KAS": "L1,POW",
    "APT": "L1,POS",
    "SUI": "L1,POS",
    "SEI": "L1,POS",
    "TIA": "L1,POS",
    "INJ": "L1,POS",
    "CFX": "L1,POS",
    "IMX": "L1,POS",
    "RONIN": "L1,POS",
    "TON": "L1,POS",
    "STX": "L1,POW",
    "BSV": "L1,POW",
    "ZEC": "L1,POW,Privacy",
    "XMR": "L1,POW,Privacy",
    "DASH": "L1,POW,Privacy",
    "RVN": "L1,POW",
    "BEAMX": "L1,Privacy",
    "LSK": "L1,POS",
    "NEO": "L1",
    "QTUM": "L1",
    "WAVES": "L1",
    "ZIL": "L1",
    "ICX": "L1",
    "ONT": "L1",
    "VET": "L1",
    "THETA": "L1",
    "IOTA": "L1",
    "XTZ": "L1,POS",
    "EOS": "L1",
    "KSM": "L1,POS",
    "CELO": "L1,POS",
    "ROSE": "L1",
    "SCRT": "L1,Privacy",
    "METIS": "L2",
    "MOVR": "L1",
    "GLMR": "L1,POS",
    "ASTR": "L1,POS",
    "DYM": "L1",
    "SAGA": "L1",
    "OMNI": "L1",
    "ZK": "L2",
    "STRK": "L2",
    "LINEA": "L2",
    "SCROLL": "L2",
    "MANTLE": "L2",
    "BLAST": "L2",
    "MODE": "L2",
    "SONIC": "L1,POS",
    "TAIKO": "L2",
    "ZRO": "L2",
    "L2": "L2",
    # L2
    "ARB": "L2",
    "OP": "L2",
    "MATIC": "L2",
    "POL": "L2",
    "MANTA": "L2",
    "SKL": "L2",
    "BOBA": "L2",
    "LRC": "L2",
    "ZEN": "L1,POW,Privacy",
    "BNB": "L1,CEX",
    # Meme
    "DOGE": "Meme",
    "SHIB": "Meme",
    "PEPE": "Meme",
    "FLOKI": "Meme",
    "BONK": "Meme",
    "WIF": "Meme",
    "MEME": "Meme",
    "TURBO": "Meme",
    "BRETT": "Meme",
    "POPCAT": "Meme",
    "MEW": "Meme",
    "BOME": "Meme",
    "PONKE": "Meme",
    "SLERF": "Meme",
    "MYRO": "Meme",
    "FARTCOIN": "Meme",
    "TRUMP": "Meme",
    "MELANIA": "Meme",
    "DOGS": "Meme",
    "CATI": "Meme",
    "DEGEN": "Meme",
    "BANANA": "Meme",
    "COOKIE": "Meme",
    "GOAT": "Meme",
    "MOODENG": "Meme",
    "BOB": "Meme",
    "NEIRO": "Meme",
    "TNSR": "NFT",
    "ORDI": "BRC-20",
    "SATS": "BRC-20",
    "RATS": "BRC-20",
    "MOG": "Meme",
    # DeFi
    "UNI": "DeFi,DEX",
    "AAVE": "DeFi,Lending",
    "LINK": "DeFi,Oracle",
    "MKR": "DeFi,Lending",
    "SNX": "DeFi,Derivatives",
    "CRV": "DeFi,DEX",
    "COMP": "DeFi,Lending",
    "YFI": "DeFi,Yield",
    "SUSHI": "DeFi,DEX",
    "1INCH": "DeFi,DEX",
    "BAL": "DeFi,DEX",
    "DYDX": "DeFi,Derivatives",
    "GMX": "DeFi,Derivatives",
    "LDO": "DeFi,Liquid Staking",
    "RPL": "DeFi,Liquid Staking",
    "PENDLE": "DeFi,Yield",
    "RUNE": "DeFi,DEX",
    "CAKE": "DeFi,DEX",
    "JOE": "DeFi,DEX",
    "RAY": "DeFi,DEX",
    "ORCA": "DeFi,DEX",
    "JUP": "DeFi,DEX",
    "WOO": "DeFi,DEX",
    "DODO": "DeFi,DEX",
    "BAND": "DeFi,Oracle",
    "API3": "DeFi,Oracle",
    "GRT": "DeFi,Oracle",
    "FXS": "DeFi,Stablecoin",
    "LQTY": "DeFi,Lending",
    "CVX": "DeFi,Yield",
    "REN": "DeFi,Bridge",
    "OCEAN": "DeFi,Data",
    "FET": "AI",
    "AGIX": "AI",
    "RENDER": "AI",
    "TAO": "AI",
    "WLD": "AI",
    "ARKM": "AI",
    "NMR": "AI",
    "JASMY": "IoT",
    "FIL": "Storage",
    "AR": "Storage",
    "STORJ": "Storage",
    "BLZ": "Storage",
    "ANKR": "Infrastructure",
    "CHZ": "Gaming,Fan Token",
    "SAND": "Gaming,Metaverse",
    "MANA": "Gaming,Metaverse",
    "AXS": "Gaming",
    "ENJ": "Gaming,NFT",
    "GALA": "Gaming",
    "IMX": "Gaming,L2",
    "MAGIC": "Gaming",
    "YGG": "Gaming",
    "ILV": "Gaming",
    "ALICE": "Gaming",
    "SUPER": "Gaming",
    "PIXEL": "Gaming",
    "PORTAL": "Gaming",
    "XAI": "AI,Gaming",
    "DEFI": "Index,DeFi",
    "PERP": "DeFi,Derivatives",
    "BIGTIME": "Gaming",
    "ACE": "Gaming",
    "NFP": "Gaming",
    "PENGU": "Meme",
    "PEOPLE": "Meme",
    "ENS": "NFT,Name Service",
    "BLUR": "NFT",
    "APE": "NFT",
    "GMT": "Gaming",
    "HOOK": "Gaming",
    "HIGH": "Gaming",
    "TLM": "Gaming",
    "ALPHA": "Gaming",
    "SFP": "DeFi",
    "BEL": "DeFi",
    "LINA": "DeFi",
    "C98": "CEX",
    "BNT": "DeFi",
    "TRU": "DeFi",
    "BICO": "DeFi",
    "STG": "DeFi,Bridge",
    "RDNT": "DeFi,Lending",
    "HFT": "DeFi,DEX",
    "MAV": "DeFi,DEX",
    "SSV": "DeFi,Staking",
    "EIGEN": "DeFi,Restaking",
    "ETHFI": "DeFi,Restaking",
    "SWELL": "DeFi,Restaking",
    "PUFFER": "DeFi,Restaking",
    "LISTA": "DeFi,Stablecoin",
    "ENA": "DeFi,Stablecoin",
    "USDC": "Stablecoin",
    "FRAX": "Stablecoin",
    "PAXG": "RWA",
    "BTCDOM": "Index",
    "BTCST": "Liquid Staking",
    "STX": "L1,POW",
    "ALT": "L2",
    "ZETA": "L1",
    "JTO": "DeFi",
    "PYTH": "DeFi,Oracle",
    "JUP": "DeFi,DEX",
    "W": "Meme",
    "NOT": "Meme",
    "BB": "L2",
    "REZ": "L2",
    "OMNI": "L1",
    "AEVO": "DeFi,Derivatives",
    "ENA": "DeFi",
    "TNSR": "NFT",
    "SAGA": "L1",
    "TAO": "AI",
    "WLD": "AI",
    "HYPE": "L1",
    "VIRTUAL": "Gaming",
    "DRIFT": "DeFi,Derivatives",
    "GRASS": "DeFi,AI",
    "IO": "Depin",
    "ZRO": "L2",
    "EIGEN": "DeFi",
    "APT": "L1",
    "SUI": "L1",
    "SEI": "L1",
    "TIA": "L1",
    "INJ": "L1",
    "OP": "L2",
    "ARB": "L2",
    "STRK": "L2",
    "ZK": "L2",
    "MANTA": "L2",
    "METIS": "L2",
    "BLAST": "L2",
    "MODE": "L2",
    "LINEA": "L2",
    "SCROLL": "L2",
    "MANTLE": "L2",
    "LPT": "Infrastructure",
    "RENDER": "AI",
    "AKT": "Infrastructure",
    "FET": "AI",
    "AGIX": "AI",
    "OCEAN": "DeFi,AI",
    "NTRN": "L1",
    "TIA": "L1",
    "DYM": "L1",
    "PENDLE": "DeFi",
    "ONDO": "RWA",
    "JUP": "DeFi",
    "WIF": "Meme",
    "BOME": "Meme",
    "ENA": "DeFi",
    "ETHFI": "DeFi",
    "REZ": "L2",
    "BB": "L2",
    "NOT": "Meme",
    "IO": "Depin",
    "ZRO": "L2",
    "CHEEMS": "Meme",
    "WHY": "Meme",
    "XEC": "L1",
    "LUNC": "L1",
    "LUNA2": "L1",
    "USTC": "Stablecoin",
    "FTT": "CEX",
    "HT": "CEX",
    "LEO": "CEX",
    "CRO": "CEX",
    "OKB": "CEX",
    "KCS": "CEX",
    "GT": "CEX",
    "MX": "CEX",
    "BNX": "DeFi,Derivatives",
    "GTC": "NFT",
    "AUDIO": "Media",
    "RAD": "NFT",
    "BADGER": "DeFi",
    "TRB": "DeFi,Oracle",
    "POLY": "L2",
    "MASK": "DeFi",
    "ID": "Gaming",
    "ARPA": "Privacy",
    "CTSI": "L2",
    "POLYX": "L1",
    "GAS": "L1",
    "STPT": "L2",
    "CKB": "L1",
    "ACH": "L2",
    "EDU": "Gaming",
    "SUI": "L1",
    "BLUR": "NFT",
    "ARKM": "AI",
    "COMBO": "Gaming",
    "MAV": "DeFi",
    "SEI": "L1",
    "CYBER": "L1",
    "HIFI": "DeFi",
    "ARK": "DeFi",
    "LOOM": "L2",
    "BOND": "DeFi",
    "ORBS": "Infrastructure",
    "WAXP": "Gaming",
    "RIF": "L2",
    "POWR": "Energy",
    "SNT": "DeFi",
    "STEEM": "L1,Social",
    "ONG": "L1",
    "ETHW": "L1,POW",
    "JTO": "DeFi",
    "AUCTION": "NFT",
    "ACE": "Gaming",
    "NFP": "Gaming",
    "AI": "AI",
    "XAI": "AI,Gaming",
    "ONDO": "RWA",
    "ALT": "L2",
    "DYM": "L1",
    "OM": "DeFi",
    "PIXEL": "Gaming",
    "PORTAL": "Gaming",
    "GLM": "DeFi",
    "AXL": "DeFi,Bridge",
    "METIS": "L2",
    "AEVO": "DeFi",
    "VANRY": "Gaming",
    "ETHFI": "DeFi",
    "ENA": "DeFi",
    "TNSR": "NFT",
    "SAGA": "L1",
    "TAO": "AI",
    "OMNI": "L1",
    "REZ": "L2",
    "BB": "L2",
    "NOT": "Meme",
    "TURBO": "Meme",
    "ZK": "L2",
    "MEW": "Meme",
    "LISTA": "DeFi",
    "ZRO": "L2",
    "RENDER": "AI",
    "RARE": "Gaming",
    "SYN": "DeFi",
    "SYS": "L1",
    "VOXEL": "Gaming",
    "ALPACA": "DeFi",
    "SUN": "DeFi",
    "FLUX": "L1,POW",
    "BSW": "DeFi",
    "QUICK": "DeFi",
    "RPL": "DeFi",
    "POL": "L2",
    "KDA": "L1",
    "FIDA": "DeFi",
    "FIO": "Infrastructure",
    "GHST": "Gaming",
    "LOKA": "Gaming",
    "DIA": "DeFi,Oracle",
    "GOAT": "Meme",
    "SAFE": "L2",
    "SANTOS": "Fan Token",
    "PONKE": "Meme",
    "COW": "DeFi",
    "CETUS": "DeFi",
    "GRASS": "AI",
    "DEGEN": "Meme",
    "BAN": "Meme",
    "AKT": "Infrastructure",
    "SCRT": "L1,Privacy",
    "THE": "Meme",
    "MORPH": "L2",
    "KAIA": "L1",
    "AERO": "DeFi",
    "ORCA": "DeFi",
    "MOVE": "L1",
    "SPX": "Meme",
    "DEGO": "DeFi,NFT",
    "VELODROME": "DeFi",
    "MOCA": "NFT",
    "VANA": "AI",
    "USUAL": "DeFi",
    "CGPT": "AI",
    "HIVE": "L1,Social",
    "DEXE": "DeFi",
    "PHA": "Privacy",
    "SONIC": "L1",
    "PROM": "L2",
    "SOLV": "DeFi",
    "TRUMP": "Meme",
    "ANIME": "Meme",
    "VINE": "Meme",
    "BERA": "L1",
    "LAYER": "L2",
    "B3": "DeFi",
    "IP": "DeFi",
    "SHELL": "DeFi",
    "RED": "DeFi",
    "EPIC": "Gaming",
    "FORM": "DeFi",
    "BID": "DeFi",
    "PLUME": "L2",
    "NIL": "L2",
    "MAVIA": "Gaming",
    "FUN": "Gaming",
    "MLN": "DeFi",
    "GUN": "Gaming",
    "FORTH": "DeFi",
    "PROMPT": "AI",
    "FHE": "Privacy",
    "KERNEL": "L2",
    "INIT": "DeFi",
    "BANK": "Meme",
    "DEEP": "DeFi",
    "JST": "DeFi",
    "PUNDIX": "Payment",
    "CTK": "L1",
    "ALPINE": "Fan Token",
    "CVC": "Identity",
    "MERL": "Meme",
    "HYPE": "L1",
    "PUFFER": "DeFi",
    "PORT3": "DeFi",
    "SKATE": "Gaming",
    "TAIKO": "L2",
    "SQD": "Infrastructure",
    "MYX": "DeFi",
    "NEWT": "Meme",
    "DMC": "Gaming",
    "SAHARA": "DeFi",
    "BULLA": "Meme",
    "MUSDT": "Stablecoin",
    "C": "DeFi",
    "VELVET": "DeFi",
    "TAC": "Gaming",
    "ERA": "L2",
    "CVX": "DeFi",
    "SLP": "Gaming",
    "ZORA": "L2",
    "TAG": "DeFi",
    "PLAY": "Gaming",
    "CARV": "Gaming",
    "AIO": "AI",
    "BAS": "L2",
    "HEMI": "L1",
    "LINEA": "L2",
    "OPEN": "DeFi",
    "SKY": "Gaming",
    "HOLO": "Infrastructure",
    "ZKC": "L2",
    "TOSHI": "Meme",
    "0G": "Infrastructure",
    "FLUID": "DeFi",
    "COAI": "AI",
    "LIGHT": "L2",
    "EDEN": "DeFi",
    "NOM": "DeFi",
    "MON": "Meme",
    "EULA": "DeFi",
    "CLO": "DeFi",
    "RECALL": "AI",
    "LAB": "DeFi",
    "RIVER": "DeFi",
    "APR": "DeFi",
    "ON": "DeFi",
    "COMMON": "Meme",
    "KITE": "DeFi",
    "CC": "DeFi",
    "TRUST": "DeFi",
    "UAI": "AI",
    "FOLKS": "DeFi",
    "JCT": "DeFi",
    "ALLO": "DeFi",
    "CLANKER": "Meme",
    "PIEVERSE": "Gaming",
    "SENT": "DeFi",
    "BOB": "Meme",
    "IRYS": "Infrastructure",
    "POWER": "DeFi",
    "NIGHT": "DeFi",
    "CYS": "DeFi",
    "GUA": "DeFi",
    "LIT": "L2",
    "MAGMA": "L2",
    "ZAMA": "Privacy",
    "FRAX": "Stablecoin",
    "AIA": "AI",
    "AZTEC": "Privacy",
    "OPN": "DeFi",
}


def _base_symbol(currency: str) -> str:
    """BTCUSDT -> BTC, 1000PEPEUSDT -> PEPE, 1000000MOGUSDT -> MOG."""
    s = (currency or "").strip().upper()
    if not s or not s.endswith("USDT"):
        return s
    base = s[:-4]  # strip USDT
    # Strip multiplier prefix
    if base.startswith("1000000"):
        base = base[7:]
    elif base.startswith("1000"):
        base = base[4:]
    return base


def main() -> int:
    if not MARKET_DATA_PATH.exists():
        print(f"Missing {MARKET_DATA_PATH}", file=sys.stderr)
        return 1

    rows: list[dict] = []
    with open(MARKET_DATA_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            cur = (row.get("currency") or "").strip()
            if not cur:
                continue
            base = _base_symbol(cur)
            labels = SYMBOL_LABELS.get(base, "").strip()
            rows.append({"currency": cur, "labels": labels})

    LABELED_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(LABELED_PATH, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["currency", "labels"])
        w.writeheader()
        w.writerows(rows)

    filled = sum(1 for r in rows if (r.get("labels") or "").strip())
    print(f"Wrote {len(rows)} rows to {LABELED_PATH} ({filled} with labels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
